### ISSUE TITLE
when running in docker, some error happend

### ISSUE THREAD

**Issue by q921195075** [mmiscool/FC-Docker#8]
system:ubuntu 20.04
I am using a fresh, clean system and have modified the configuration according to #4, but it still won't run. Here is the error:
![image](https://github.com/mmiscool/FC-Docker/assets/73765190/dbe10862-966f-4eae-9f00-ac1e3ba877ea)

It's stuck here the whole time
![image](https://github.com/mmiscool/FC-Docker/assets/73765190/d684c932-0251-4d5b-bf6f-5afc21635416)

**Comment by q921195075** [comment]
oopss I just download master files , not include submodules

**Comment by mmiscool** [comment]
Its all working now right? 

I tried to keep it simple and include a full set of instructions to spin up a server.

**Comment by q921195075** [comment]
> Its all working now right?
> 
> I tried to keep it simple and include a full set of instructions to spin up a server.

yep it's working now. Maybe you could add a note：remember to download all files, inclue all file of the path external_dependencies/external/. This is the only place I've had problems. It's the first time I've ever had to download a project like this.
